###Get all users
GET http://localhost:3001/api/users HTTP/1.1

### Get a single user
GET http://localhost:3001/api/users/ralf666 HTTP/1.1

### Get a single user who doesn’t exist
GET http://localhost:3001/api/users/Rolf HTTP/1.1

### Delete a user
DELETE http://localhost:3001/api/users/Michl HTTP/1.1 

### POST a user
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Michl",
    "username": "Michl",
    "password": "Gott"
} 

### Get all festivals
GET http://localhost:3001/api/festivals HTTP/1.1


### Get a single festival
GET http://localhost:3001/api/festivals/Southside HTTP/1.1


### POST a festival
POST http://localhost:3001/api/festivals HTTP/1.1
Content-Type: application/json

{
    "name": "SUPER JULES",
    "location": "Ferropolis",
    "begin": "14.07.2022",
    "end": "17.07.2022",
    "visitors": "8000",
    "acts": "35",
    "price": "180",
    "allacts": "Adele, Arcade Fire, Bicep, Billie Eilish, Bombay Bicycle Club, Caribou, Deichkind, Digitalism, Florence + The Machine, FYE & FENNEK, Frittenbude, Giant Rooks, Harry Styles, Herbert Grönemeyer,  HVOB, Kalipo, Justice, KUMMER, Lady Gaga, Little Dragon, London Grammar, Lykke Li, Maribou State, Materia, Metronomy, Nura, Nelly Furtado, Orbi, Post Malone, Sufjan Stevens, The Police, The XX, Trettmann, Two Door Cinema Club, Weval"
} 

### Delete a festival
DELETE http://localhost:3001/api/festivals/Southside HTTP/1.1




